server:
  port: 8855

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable-learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456

flowable:
  asyncExecutorActivate: true # 关闭定时任务
  databaseSchemaUpdate: true # 当Flowable发现库与数据库表结构不一致时, 会自动将数据库表结构升级至版本
logging:
  level:
    org:
      flowable: debug